# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\AbdulSalam\Documents\MyCodes\my_project\python_project\Missing Data App\Missing-Data-App\Appui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 585)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setMaximumSize(QtCore.QSize(788, 499))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 54))
        self.frame_3.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TitleLable = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.TitleLable.setFont(font)
        self.TitleLable.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"font: 7pt \"MS Shell Dlg 2\";\n"
"font: 26pt \"MS Shell Dlg 2\";\n"
"font: 20pt \"MS Shell Dlg 2\";")
        self.TitleLable.setObjectName("TitleLable")
        self.horizontalLayout.addWidget(self.TitleLable)
        self.horizontalLayout_2.addWidget(self.frame_3)
        spacerItem1 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.loadLabel = QtWidgets.QLabel(self.frame_2)
        self.loadLabel.setObjectName("loadLabel")
        self.horizontalLayout_3.addWidget(self.loadLabel)
        spacerItem2 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadDataButton = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadDataButton.setFont(font)
        self.loadDataButton.setToolTipDuration(-1)
        self.loadDataButton.setFlat(False)
        self.loadDataButton.setObjectName("loadDataButton")
        self.horizontalLayout_4.addWidget(self.loadDataButton)
        spacerItem3 = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.inputLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.inputLabel.setFont(font)
        self.inputLabel.setMouseTracking(False)
        self.inputLabel.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.inputLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputLabel.setText("")
        self.inputLabel.setObjectName("inputLabel")
        self.horizontalLayout_9.addWidget(self.inputLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.line_2 = QtWidgets.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.columnLabel = QtWidgets.QLabel(self.frame_2)
        self.columnLabel.setObjectName("columnLabel")
        self.verticalLayout_4.addWidget(self.columnLabel)
        self.splitter_2 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.indexColumnLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.indexColumnLabel.setFont(font)
        self.indexColumnLabel.setObjectName("indexColumnLabel")
        self.verticalLayout.addWidget(self.indexColumnLabel)
        self.indexComboBox = QtWidgets.QComboBox(self.widget)
        self.indexComboBox.setObjectName("indexComboBox")
        self.verticalLayout.addWidget(self.indexComboBox)
        self.widget1 = QtWidgets.QWidget(self.splitter_2)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dataColumnLable = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dataColumnLable.setFont(font)
        self.dataColumnLable.setObjectName("dataColumnLable")
        self.verticalLayout_2.addWidget(self.dataColumnLable)
        self.missingDataComboBox = QtWidgets.QComboBox(self.widget1)
        self.missingDataComboBox.setObjectName("missingDataComboBox")
        self.verticalLayout_2.addWidget(self.missingDataComboBox)
        self.verticalLayout_4.addWidget(self.splitter_2)
        self.line_7 = QtWidgets.QFrame(self.frame_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_4.addWidget(self.line_7)
        self.methodLabel = QtWidgets.QLabel(self.frame_2)
        self.methodLabel.setObjectName("methodLabel")
        self.verticalLayout_4.addWidget(self.methodLabel)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.methodsComboBox = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.methodsComboBox.setFont(font)
        self.methodsComboBox.setObjectName("methodsComboBox")
        self.methodsComboBox.addItem("")
        self.methodsComboBox.addItem("")
        self.methodsComboBox.addItem("")
        self.methodsComboBox.addItem("")
        self.methodsComboBox.addItem("")
        self.methodsComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.methodsComboBox)
        spacerItem5 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.line_3 = QtWidgets.QFrame(self.frame_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.estimateLabel = QtWidgets.QLabel(self.frame_2)
        self.estimateLabel.setObjectName("estimateLabel")
        self.horizontalLayout_6.addWidget(self.estimateLabel)
        spacerItem6 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.splitter = QtWidgets.QSplitter(self.frame_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.estimateDataButton = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.estimateDataButton.setFont(font)
        self.estimateDataButton.setToolTipDuration(-1)
        self.estimateDataButton.setFlat(False)
        self.estimateDataButton.setObjectName("estimateDataButton")
        self.progressBar = QtWidgets.QProgressBar(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.splitter)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.outputLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.outputLabel.setFont(font)
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.horizontalLayout_8.addWidget(self.outputLabel)
        spacerItem7 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_11.addWidget(self.frame_2)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_11.addWidget(self.line_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/UniLogo1.jpg"))
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.guideLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.guideLabel.setFont(font)
        self.guideLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.guideLabel.setObjectName("guideLabel")
        self.verticalLayout_3.addWidget(self.guideLabel)
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_3.addWidget(self.line_6)
        self.userLabel = QtWidgets.QLabel(self.frame)
        self.userLabel.setObjectName("userLabel")
        self.verticalLayout_3.addWidget(self.userLabel)
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addWidget(self.frame)
        self.horizontalLayout_12.addWidget(self.frame_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionRefresh = QtWidgets.QAction(MainWindow)
        self.actionRefresh.setObjectName("actionRefresh")
        self.actionAbout_App = QtWidgets.QAction(MainWindow)
        self.actionAbout_App.setObjectName("actionAbout_App")
        self.actionDownload_Latest_Version = QtWidgets.QAction(MainWindow)
        self.actionDownload_Latest_Version.setObjectName("actionDownload_Latest_Version")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionClear_All)
        self.menuEdit.addAction(self.actionRefresh)
        self.menuHelp.addAction(self.actionAbout_App)
        self.menuHelp.addAction(self.actionDownload_Latest_Version)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.inputLabel.setBuddy(MainWindow.input directry)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLable.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#005500;\">APPLICATION FOR ESTIMATING MISSING DATA</span></p></body></html>"))
        self.loadLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ff0000;\">1- click to load the csv data</span></p></body></html>"))
        self.loadDataButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">Click to load the dataset with missing data</span></p></body></html>"))
        self.loadDataButton.setStatusTip(_translate("MainWindow", "Load Data Button"))
        self.loadDataButton.setText(_translate("MainWindow", "Load "))
        self.columnLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ff0000;\">2- select the index column and the missing data column</span></p></body></html>"))
        self.indexColumnLabel.setText(_translate("MainWindow", "Index Column"))
        self.indexComboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Click to select the index column</span></p></body></html>"))
        self.dataColumnLable.setText(_translate("MainWindow", "Missing data Column"))
        self.missingDataComboBox.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Click to select the column with missing data</span></p></body></html>"))
        self.methodLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ff0000;\">3- select the best fit method of estimation</span></p></body></html>"))
        self.methodsComboBox.setItemText(0, _translate("MainWindow", "Last Observation Carried Forward"))
        self.methodsComboBox.setItemText(1, _translate("MainWindow", "Next Observation Carried Backward"))
        self.methodsComboBox.setItemText(2, _translate("MainWindow", "Mean substitution"))
        self.methodsComboBox.setItemText(3, _translate("MainWindow", "Median substitution"))
        self.methodsComboBox.setItemText(4, _translate("MainWindow", "Bayesian ridge model"))
        self.methodsComboBox.setItemText(5, _translate("MainWindow", "Random Forest model"))
        self.estimateLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-style:italic; color:#ff0000;\">4- estimate missing data</span></p></body></html>"))
        self.estimateDataButton.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">Click to fill in the missing data</span></p></body></html>"))
        self.estimateDataButton.setStatusTip(_translate("MainWindow", "Estimate Button"))
        self.estimateDataButton.setText(_translate("MainWindow", "Estimate"))
        self.guideLabel.setText(_translate("MainWindow", "Brief Guide\n"
"This Application estimate missing data. \n"
"Follow the step below:\n"
"1. Prepare a univariate data in csv format i.e \n"
"a data having an index column and a colunm having a missing data.\n"
"2. Click the <Load> Button to import the data.\n"
"3.Select the method that best fit the data. \n"
"4. Click the <Estimate> Button for imputing missing data"))
        self.userLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Designed and written by Abdulazeez Abdulsalam A.</span></p><p><span style=\" font-size:10pt;\">Program: M.Sc Final Project</span></p><p><span style=\" font-size:10pt;\">Department: Surveying and Geoinformatics</span></p><p><span style=\" font-size:10pt;\">Supervisor: Ayodele O. G (Phd)</span></p></body></html>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open "))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh"))
        self.actionAbout_App.setText(_translate("MainWindow", "About App."))
        self.actionDownload_Latest_Version.setText(_translate("MainWindow", "Download Latest Version"))
import resources_rc
